### ISSUE TITLE
`kytos napps list` output formatting crashing on docker

### ISSUE THREAD

**Issue by viniciusarcanjo** [kytos/kytos-utils#168]
To reproduce run:

```
docker run -i -t kytos/tryfirst:2018.1b1                                                                                                                                                            
```
1 - Install kytos/of_core
2 - Run kytos napps list

```
root@49514ecd826b:/app# kytosd -f
2018-03-15 18:11:24,427 - INFO [kytos.core.logs] (MainThread) Logging config file "/etc/kytos/logging
2018-03-15 18:11:24,428 - INFO [kytos.core.controller] (MainThread) /var/run/kytos
2018-03-15 18:11:24,428 - INFO [kytos.core.controller] (MainThread) Starting Kytos - Kytos Controller
2018-03-15 18:11:24,429 - WARNING [werkzeug] (API server) WebSocket transport not available. Install
2018-03-15 18:11:24,429 - INFO [kytos.core.tcp_server] (TCP server) Kytos listening at 0.0.0.0:6633
root@f105bde50393:/#
root@f105bde50393:/#
root@f105bde50393:/#
root@f105bde50393:/# kytos napps list
WARNING Config file /root/.kytosrc not found.
WARNING Creating a new empty config file.
No NApps found.
root@f105bde50393:/# kytos napps list
No NApps found.
root@f105bde50393:/# kytos napps list

No NApps found.
root@f105bde50393:/#
root@f105bde50393:/# kytos napps install kytos/of_core
INFO    NApp kytos/of_core:
INFO      Searching local NApp...
INFO      Not found. Downloading from NApps Server...
INFO      Downloaded and installed.
INFO      Enabling...
INFO      Enabled.
root@f105bde50393:/# kytos napps list
Traceback (most recent call last):
  File "/usr/local/bin/kytos", line 42, in <module>
    parse(argv)
  File "/usr/local/lib/python3.6/dist-packages/kytos/cli/commands/napps/parser.py", line 49, in parse
    call(sys.argv[2], args)
  File "/usr/local/lib/python3.6/dist-packages/kytos/cli/commands/napps/parser.py", line 59, in call
    func(args)
  File "/usr/local/lib/python3.6/dist-packages/kytos/cli/commands/napps/api.py", line 217, in list
    cls.print_napps(napps_ordered)
  File "/usr/local/lib/python3.6/dist-packages/kytos/cli/commands/napps/api.py", line 236, in print_n
apps
    print(header.format('Status', 'NApp ID', 'Description'))
ValueError: Sign not allowed in string format specifier
root@f105bde50393:/#
```

**Comment by hdiogenes** [comment]
This can be easily reproduced just by running `kytos napps list` on a really small terminal window.

![captura de tela 2018-03-15 as 16 23 57](https://user-images.githubusercontent.com/3139/37486508-6baa09e8-286d-11e8-87d3-070bd2a70e3b.png)

**Comment by hdiogenes** [comment]
PR #169 fixes this.
