### ISSUE TITLE
kytos napps list (and other commands) is broken

### ISSUE THREAD

**Issue by beraldoleal** [kytos/kytos-utils#41]
```
beraldo@anita:/usr/src/beraldo/ncc/github/kytos-utils$ kytos napps list
Traceback (most recent call last):
  File "/usr/lib/python3.5/configparser.py", line 786, in get
    value = d[option]
  File "/usr/lib/python3.5/collections/__init__.py", line 877, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.5/collections/__init__.py", line 869, in __missing__
    raise KeyError(key)
KeyError: 'installed_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/kytos", line 4, in <module>
    __import__('pkg_resources').run_script('kytos-utils==0.1.0', 'kytos')
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 744, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.5/dist-packages/pkg_resources/__init__.py", line 1499, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.5/dist-packages/kytos_utils-0.1.0-py3.5.egg/EGG-INFO/scripts/kytos", line 54, in <module>
    parse(argv)
  File "/usr/local/lib/python3.5/dist-packages/kytos_utils-0.1.0-py3.5.egg/kytos/cli/commands/napps/parser.py", line 44, in parse
    call(sys.argv[2], args)
  File "/usr/local/lib/python3.5/dist-packages/kytos_utils-0.1.0-py3.5.egg/kytos/cli/commands/napps/parser.py", line 53, in call
    func(args)
  File "/usr/local/lib/python3.5/dist-packages/kytos_utils-0.1.0-py3.5.egg/kytos/cli/commands/napps/api.py", line 152, in list
    mgr = NAppsManager()
  File "/usr/local/lib/python3.5/dist-packages/kytos_utils-0.1.0-py3.5.egg/kytos/utils/napps.py", line 40, in __init__
    self._installed = Path(self._config.get('napps', 'installed_path'))
  File "/usr/lib/python3.5/configparser.py", line 789, in get
    raise NoOptionError(option, section)
configparser.NoOptionError: No option 'installed_path' in section: 'napps'
```

**Comment by diraol** [comment]
@beraldoleal you used python3.5... this could have caused the problem. Please, try it with Python 3.6 instead.

**Comment by beraldoleal** [comment]
Yes, sure. I forgot about this small detail! :) Thanks.
