### ISSUE TITLE
Check requirements install in setup.py

### ISSUE THREAD

**Issue by renanrodrigo** [kytos/kytos-utils#46]
Right after running `python3.6 setup.py install`, the command `kytos --help` breaks with missing packages.

**Comment by beraldoleal** [comment]
Please, paste output here.

**Comment by renanrodrigo** [comment]
Traceback (most recent call last):
  File "/usr/local/bin/kytos", line 4, in <module>
    __import__('pkg_resources').run_script('kytos-utils==0.1.0', 'kytos')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/kytos_utils-0.1.0-py3.6.egg/EGG-INFO/scripts/kytos", line 40, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/usr/local/bin/kytos", line 4, in <module>
    __import__('pkg_resources').run_script('kytos-utils==0.1.0', 'kytos')
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 719, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/dist-packages/kytos_utils-0.1.0-py3.6.egg/EGG-INFO/scripts/kytos", line 40, in <module>
    from docopt import docopt
ModuleNotFoundError: No module named 'docopt'
